-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 15:37:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel_de_asiana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_de_asiana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_de_asiana` DEFAULT CHARACTER SET utf8 ;
USE `hotel_de_asiana` ;

-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`family` (
  `head_nic` INT(10) NOT NULL,
  `head_name` VARCHAR(45) NOT NULL,
  `head_gender` CHAR(1) NOT NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`head_nic`),
  INDEX `fk_family_guest_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_family_guest`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`individual` (
  `nic` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`nic`),
  INDEX `fk_individual_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_individual_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `billing_address` VARCHAR(100) NOT NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`contact` (
  `contact_no` INT(10) NOT NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`contact_no`, `guest_id`),
  INDEX `fk_contact_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`room` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `rate` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`guest_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`guest_room` (
  `guest_id` INT NOT NULL,
  `room_no` INT NOT NULL,
  `check_in_date` DATETIME NOT NULL,
  `check_out_date` DATETIME NOT NULL,
  PRIMARY KEY (`guest_id`, `room_no`, `check_in_date`),
  INDEX `fk_guest_has_room_room1_idx` (`room_no` ASC) VISIBLE,
  INDEX `fk_guest_has_room_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_has_room_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_guest_has_room_room1`
    FOREIGN KEY (`room_no`)
    REFERENCES `hotel_de_asiana`.`room` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`food` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` VARCHAR(10) NOT NULL,
  `portion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`food_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`food_order` (
  `guest_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`guest_id`, `food_id`, `date`),
  INDEX `fk_guest_has_food_food1_idx` (`food_id` ASC) VISIBLE,
  INDEX `fk_guest_has_food_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_has_food_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_guest_has_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `hotel_de_asiana`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `rate` DECIMAL(10,2) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`guest_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`guest_facility` (
  `guest_id` INT NOT NULL,
  `facility_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`guest_id`, `facility_id`),
  INDEX `fk_guest_has_facility_facility1_idx` (`facility_id` ASC) VISIBLE,
  INDEX `fk_guest_has_facility_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_guest_has_facility_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_guest_has_facility_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `hotel_de_asiana`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `contact_no` INT(10) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `salary_grade` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`indoor_req`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`indoor_req` (
  `facility_id` INT NOT NULL,
  `reservation_req_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`facility_id`, `reservation_req_name`),
  INDEX `fk_indoor_req_facility1_idx` (`facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_indoor_req_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `hotel_de_asiana`.`facility` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`outdoor_guiding_req`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`outdoor_guiding_req` (
  `facility_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`facility_id`, `name`),
  CONSTRAINT `fk_outdoor_guiding_req_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `hotel_de_asiana`.`facility` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`outdoor_special_req`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`outdoor_special_req` (
  `facility_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`facility_id`, `name`),
  CONSTRAINT `fk_outdoor_special_req_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `hotel_de_asiana`.`facility` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`receptionist` (
  `id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Receptionist_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Receptionist_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hotel_de_asiana`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`management` (
  `id` INT NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_management_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_management_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hotel_de_asiana`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`kitchen_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`kitchen_staff` (
  `id` INT NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  `experience` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kitchen_staff_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_kitchen_staff_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hotel_de_asiana`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`cleaning_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`cleaning_staff` (
  `id` INT NOT NULL,
  `work` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cleaning_staff_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_cleaning_staff_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hotel_de_asiana`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`chef` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kitchen_staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chef_kitchen_staff1_idx` (`kitchen_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_chef_kitchen_staff1`
    FOREIGN KEY (`kitchen_staff_id`)
    REFERENCES `hotel_de_asiana`.`kitchen_staff` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`specility_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`specility_area` (
  `specility_area` VARCHAR(45) NOT NULL,
  `chef_id` INT NOT NULL,
  PRIMARY KEY (`specility_area`, `chef_id`),
  INDEX `fk_specility_area_chef1_idx` (`chef_id` ASC) VISIBLE,
  CONSTRAINT `fk_specility_area_chef1`
    FOREIGN KEY (`chef_id`)
    REFERENCES `hotel_de_asiana`.`chef` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`support_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`support_staff` (
  `id` INT NOT NULL,
  `contract_period` INT NOT NULL,
  `kitchen_staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_support_staff_kitchen_staff1_idx` (`kitchen_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_support_staff_kitchen_staff1`
    FOREIGN KEY (`kitchen_staff_id`)
    REFERENCES `hotel_de_asiana`.`kitchen_staff` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`waiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`waiter` (
  `id` INT NOT NULL,
  `kitchen_staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_waiter_kitchen_staff1_idx` (`kitchen_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_waiter_kitchen_staff1`
    FOREIGN KEY (`kitchen_staff_id`)
    REFERENCES `hotel_de_asiana`.`kitchen_staff` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`specility_style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`specility_style` (
  `waiter_id` INT NOT NULL,
  `specility_style` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`waiter_id`, `specility_style`),
  CONSTRAINT `fk_specility_style_waiter1`
    FOREIGN KEY (`waiter_id`)
    REFERENCES `hotel_de_asiana`.`waiter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`handle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`handle` (
  `receptionist_id` INT NOT NULL,
  `guest_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`receptionist_id`, `guest_id`, `date`),
  INDEX `fk_receptionist_has_guest_guest1_idx` (`guest_id` ASC) VISIBLE,
  INDEX `fk_receptionist_has_guest_receptionist1_idx` (`receptionist_id` ASC) VISIBLE,
  CONSTRAINT `fk_receptionist_has_guest_receptionist1`
    FOREIGN KEY (`receptionist_id`)
    REFERENCES `hotel_de_asiana`.`receptionist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_receptionist_has_guest_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`clean`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`clean` (
  `room_no` INT NOT NULL,
  `cleaning_staff_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`room_no`, `cleaning_staff_id`, `date`),
  INDEX `fk_room_has_cleaning_staff_cleaning_staff1_idx` (`cleaning_staff_id` ASC) VISIBLE,
  INDEX `fk_room_has_cleaning_staff_room1_idx` (`room_no` ASC) VISIBLE,
  CONSTRAINT `fk_room_has_cleaning_staff_room1`
    FOREIGN KEY (`room_no`)
    REFERENCES `hotel_de_asiana`.`room` (`no`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_room_has_cleaning_staff_cleaning_staff1`
    FOREIGN KEY (`cleaning_staff_id`)
    REFERENCES `hotel_de_asiana`.`cleaning_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`facility_manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`facility_manage` (
  `facility_id` INT NOT NULL,
  `management_id` INT NOT NULL,
  PRIMARY KEY (`facility_id`, `management_id`),
  INDEX `fk_facility_has_management_management1_idx` (`management_id` ASC) VISIBLE,
  INDEX `fk_facility_has_management_facility1_idx` (`facility_id` ASC) VISIBLE,
  CONSTRAINT `fk_facility_has_management_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `hotel_de_asiana`.`facility` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_facility_has_management_management1`
    FOREIGN KEY (`management_id`)
    REFERENCES `hotel_de_asiana`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`prepare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`prepare` (
  `chef_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  PRIMARY KEY (`chef_id`, `food_id`),
  INDEX `fk_chef_has_food_food1_idx` (`food_id` ASC) VISIBLE,
  INDEX `fk_chef_has_food_chef1_idx` (`chef_id` ASC) VISIBLE,
  CONSTRAINT `fk_chef_has_food_chef1`
    FOREIGN KEY (`chef_id`)
    REFERENCES `hotel_de_asiana`.`chef` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chef_has_food_food1`
    FOREIGN KEY (`food_id`)
    REFERENCES `hotel_de_asiana`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_de_asiana`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`bill` (
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `guest_id` INT NOT NULL,
  PRIMARY KEY (`date`, `guest_id`),
  INDEX `fk_bill_guest1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_bill_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_de_asiana`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `hotel_de_asiana` ;

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`receptionist_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`receptionist_view` (`employee_id` INT, `name` INT, `gender` INT, `contact_no` INT, `start_date` INT, `salary_grade` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`cleaning_staff_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`cleaning_staff_view` (`employee_id` INT, `cleaning_staff_id` INT, `name` INT, `gender` INT, `contact_no` INT, `start_date` INT, `salary_grade` INT, `work` INT, `location` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`manager_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`manager_view` (`employee_id` INT, `manager_id` INT, `name` INT, `gender` INT, `contact_no` INT, `start_date` INT, `salary_grade` INT, `grade` INT, `designation` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`kitchen_staff_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`kitchen_staff_view` (`employee_id` INT, `kitchen_id` INT, `name` INT, `gender` INT, `contact_no` INT, `start_date` INT, `grade` INT, `experience` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`support_staff_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`support_staff_view` (`support_id` INT, `contract_period` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`waiter_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`waiter_view` (`waiter_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`chef_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`chef_view` (`chef_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hotel_de_asiana`.`facility_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_de_asiana`.`facility_view` (`manager_id` INT, `manager_name` INT);

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`receptionist_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`receptionist_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `receptionist_view` AS 
	SELECT 
		e.id as employee_id, r.id as receptionist_id, e.name, e.gender, e.contact_no, e.start_date, e.salary_grade 
	FROM employee e JOIN 
		receptionist r ON e.id = r.employee_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`cleaning_staff_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`cleaning_staff_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `cleaning_staff_view` AS 
	SELECT 
		e.id as employee_id, c.id as cleaning_staff_id, e.name, e.gender, e.contact_no, e.start_date, e.salary_grade, c.work, c.location 
	FROM employee e JOIN 
		cleaning_staff c ON e.id = c.employee_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`manager_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`manager_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `manager_view` AS 
	SELECT 
		e.id as employee_id, m.id as manager_id, e.name, e.gender, e.contact_no, e.start_date, e.salary_grade, m.grade, m.designation
	FROM employee e JOIN 
		management m ON e.id = m.employee_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`kitchen_staff_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`kitchen_staff_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `kitchen_staff_view` AS 
	SELECT 
		e.id as employee_id, k.id as kitchen_id, e.name, e.gender, e.contact_no, e.start_date, k.grade, k.experience
	FROM employee e JOIN 
		kitchen_staff k ON e.id = k.employee_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`support_staff_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`support_staff_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `support_staff_view` AS 
	SELECT 
		k.*, s.id as support_id, s.contract_period 
    FROM kitchen_staff_view k 
    JOIN support_staff s ON 
        s.kitchen_staff_id = k.kitchen_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`waiter_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`waiter_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `waiter_view` AS 
	SELECT 
		k.*, w.id as waiter_id 
    FROM kitchen_staff_view k 
    JOIN waiter w ON 
        w.kitchen_staff_id = k.kitchen_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`chef_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`chef_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `chef_view` AS 
	SELECT 
		k.*, c.id as chef_id 
    FROM kitchen_staff_view k 
    JOIN chef c ON 
        c.kitchen_staff_id = k.kitchen_id
;

-- -----------------------------------------------------
-- View `hotel_de_asiana`.`facility_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_de_asiana`.`facility_view`;
USE `hotel_de_asiana`;
CREATE  OR REPLACE VIEW `facility_view` AS
	SELECT 
		f.*, m.manager_id as manager_id, m.name as manager_name
	FROM facility f
    JOIN facility_manage r ON f.id = r.facility_id
    JOIN manager_view m ON m.manager_id = r.management_id
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
